
services:
  db:
    image: postgres:18-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DOCKER_DB_NAME}
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
    ports:
      - "${DOCKER_DB_PORT}:5432"
    volumes:
          - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
